// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProyectoApi.Models
{
    public partial class Conductor
    {
        public Conductor()
        {
            Destinos = new HashSet<Destino>();
        }

        public int IdConductor { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Nidentificacion { get; set; }
        public string Ntelefono { get; set; }
        public string Correo { get; set; }
        public string Licencia { get; set; }
        public int IdUsuarioRegistro { get; set; }
        public DateTime? FechaRegistro { get; set; }

        public virtual Usuario IdUsuarioRegistroNavigation { get; set; }
        public virtual ICollection<Destino> Destinos { get; set; }
    }
}