// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProyectoApi.Models
{
    public partial class DatosUsuario
    {
        public int IdDatos { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Nidentificacion { get; set; }
        public int IdUsuario { get; set; }
        public DateTime? FechaRegistro { get; set; }

        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}