// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace ProyectoApi.Models
{
    public partial class Destino
    {
        public Destino()
        {
            Retornos = new HashSet<Retorno>();
            Salida = new HashSet<Salida>();
        }

        public int IdDestino { get; set; }
        public string Descripcion { get; set; }
        public string Direccion { get; set; }
        public int IdDepartamento { get; set; }
        public int IdMunicipio { get; set; }
        public int IdUnidad { get; set; }
        public int IdConductor { get; set; }
        public int IdTipoViaje { get; set; }
        public int IdUsuarioRegistro { get; set; }
        public DateTime? FechaRegistro { get; set; }

        [JsonIgnore]
        public virtual Conductor IdConductorNavigation { get; set; }
        [JsonIgnore]
        public virtual Departamento IdDepartamentoNavigation { get; set; }
        [JsonIgnore]
        public virtual Municipio IdMunicipioNavigation { get; set; }
        [JsonIgnore]
        public virtual TipoViaje IdTipoViajeNavigation { get; set; }
        [JsonIgnore]
        public virtual Unidad IdUnidadNavigation { get; set; }
        [JsonIgnore]
        public virtual Usuario IdUsuarioRegistroNavigation { get; set; }
        [JsonIgnore]
        public virtual ICollection<Retorno> Retornos { get; set; }
        [JsonIgnore]
        public virtual ICollection<Salida> Salida { get; set; }
    }
}