// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProyectoApi.Models
{
    public partial class Unidad
    {
        public Unidad()
        {
            Destinos = new HashSet<Destino>();
        }

        public int IdUnidad { get; set; }
        public string Nplaca { get; set; }
        public string Modelo { get; set; }
        public string Marca { get; set; }
        public string Descripcion { get; set; }
        public int IdUsuarioRegistro { get; set; }
        public DateTime? FechaRegistro { get; set; }

        public virtual Usuario IdUsuarioRegistroNavigation { get; set; }
        public virtual ICollection<Destino> Destinos { get; set; }
    }
}